//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsGUI.ServiceReferenceSmartWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSmartWCF.ISmartWCFService")]
    public interface ISmartWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWCFService/getFilmList", ReplyAction="http://tempuri.org/ISmartWCFService/getFilmListResponse")]
        FilmsDTO.FilmDTO[] getFilmList(int offset, int nbr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWCFService/getFilmList", ReplyAction="http://tempuri.org/ISmartWCFService/getFilmListResponse")]
        System.Threading.Tasks.Task<FilmsDTO.FilmDTO[]> getFilmListAsync(int offset, int nbr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWCFService/CountFilm", ReplyAction="http://tempuri.org/ISmartWCFService/CountFilmResponse")]
        int CountFilm();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWCFService/CountFilm", ReplyAction="http://tempuri.org/ISmartWCFService/CountFilmResponse")]
        System.Threading.Tasks.Task<int> CountFilmAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWCFService/UpdateFilm", ReplyAction="http://tempuri.org/ISmartWCFService/UpdateFilmResponse")]
        bool UpdateFilm(int idFilm, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWCFService/UpdateFilm", ReplyAction="http://tempuri.org/ISmartWCFService/UpdateFilmResponse")]
        System.Threading.Tasks.Task<bool> UpdateFilmAsync(int idFilm, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWCFService/GetData", ReplyAction="http://tempuri.org/ISmartWCFService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWCFService/GetData", ReplyAction="http://tempuri.org/ISmartWCFService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWCFService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISmartWCFService/GetDataUsingDataContractResponse")]
        SmartWCFService.CompositeType GetDataUsingDataContract(SmartWCFService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWCFService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISmartWCFService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SmartWCFService.CompositeType> GetDataUsingDataContractAsync(SmartWCFService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmartWCFServiceChannel : FilmsGUI.ServiceReferenceSmartWCF.ISmartWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartWCFServiceClient : System.ServiceModel.ClientBase<FilmsGUI.ServiceReferenceSmartWCF.ISmartWCFService>, FilmsGUI.ServiceReferenceSmartWCF.ISmartWCFService {
        
        public SmartWCFServiceClient() {
        }
        
        public SmartWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FilmsDTO.FilmDTO[] getFilmList(int offset, int nbr) {
            return base.Channel.getFilmList(offset, nbr);
        }
        
        public System.Threading.Tasks.Task<FilmsDTO.FilmDTO[]> getFilmListAsync(int offset, int nbr) {
            return base.Channel.getFilmListAsync(offset, nbr);
        }
        
        public int CountFilm() {
            return base.Channel.CountFilm();
        }
        
        public System.Threading.Tasks.Task<int> CountFilmAsync() {
            return base.Channel.CountFilmAsync();
        }
        
        public bool UpdateFilm(int idFilm, string url) {
            return base.Channel.UpdateFilm(idFilm, url);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateFilmAsync(int idFilm, string url) {
            return base.Channel.UpdateFilmAsync(idFilm, url);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public SmartWCFService.CompositeType GetDataUsingDataContract(SmartWCFService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<SmartWCFService.CompositeType> GetDataUsingDataContractAsync(SmartWCFService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
